### ISSUE TITLE
Navigation on Landing page's event slider doesn't appear

### ISSUE THREAD

**Issue by yodenharsh** [CODEX-WoU/codex-website-frontend#1]
The navigation buttons on the Swiper element in EventsAlt.jsx don't appear on the element.
In inspect element, both nav buttons have a width of 0

**Comment by HeyShinde** [comment]
You haven't added any Swiper element in EventsAlt.jsx. Might have missed to import the swiper navigation css.

**Comment by yodenharsh** [comment]
Navigation module was already imported.
The navigation css import was missing. Importing it fixes the issue

**Comment by yodenharsh** [comment]
Navigation module was already imported.
The navigation css import was missing. Importing it fixes the issue
